#!/bin/sh

apk update
apk upgrade

# Main Packages
apk add --no-cache \
    7zip aria2 coreutils curl fastfetch ffmpeg git libmagic mediainfo mkvtoolnix openjdk21-jre qbittorrent qbittorrent-nox sox tzdata wget

# Build Packages
apk add --no-cache \
    autoconf automake bash boost-dev ccache clang17-dev cmake curl-dev dpkg g++ gawk gcc gettext-dev jq libtool linux-headers make musl-dev musl-locales pv unzip xz zip

# Python Packages
apk add --no-cache py3-pip python3-dev
python -m pip install --break-system-packages --upgrade pip

# HandBrake Packages
apk add --no-cache \
    busybox jansson-dev lame-dev libass-dev libdrm-dev libjpeg-turbo-dev libtheora-dev libva-dev libvorbis-dev libvpx-dev libxml2-dev m4 meson nasm ninja numactl-dev opus-dev \
    patch pkgconf speex-dev tar x264-dev

mkdir /Temp

echo "Asia/Jakarta" >>/etc/timezone
cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# 7Zip
cd /Temp
wget https://7-zip.org/a/7z2409-linux-x64.tar.xz
7z x -o7z 7z2409-linux-x64.tar.xz
cd /Temp/7z
7z x 7z2409-linux-x64.tar
mv 7zzs /usr/bin/7z
chmod +x /usr/bin/7z

# AniDL
cd /Temp
wget https://github.com/anidl/multi-downloader-nx/releases/latest/download/multi-downloader-nx-linux-cli.7z
7z x multi-downloader-nx-linux-cli.7z
cd /Temp/multi-downloader-nx-linux-x64-cli
mv aniDL /usr/bin/anidl
chmod +x /usr/bin/anidl
anidl --service "crunchy" --dlFonts

# Bun
cd /root/Temp
curl -fsSL https://bun.sh/install | bash

# Bento4
cd /Temp
mkdir Bento4
cd /Temp/Bento4
git clone -c advice.detachedHead=false https://github.com/axiomatic-systems/Bento4.git .
cmake -DCMAKE_BUILD_TYPE=Release .
make -j$(nproc)
make install

# Code-Server
cd /Temp
curl -fsSL https://code-server.dev/install.sh | sh

# Dovi-Tool
cd /Temp
wget https://github.com/quietvoid/dovi_tool/releases/latest/dovi_tool-2.3.1-x86_64-unknown-linux-musl.tar.gz
7z x -y dovi_tool-2.3.1-x86_64-unknown-linux-musl.tar.gz
7z x -y dovi_tool-2.3.1-x86_64-unknown-linux-musl.tar
mv dovi_tool /usr/bin/dovi_tool
chmod +x /usr/bin/dovi_tool

# Gost
cd /Temp
wget https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_linux_amd64v3.tar.gz
7z x gost_2.12.0_linux_amd64v3.tar.gz
7z x gost_2.12.0_linux_amd64v3.tar
mv gost /usr/bin/gost
chmod +x /usr/bin/gost

# GPAC
cd /Temp
mkdir GPAC
cd /Temp/GPAC
git clone -c advice.detachedHead=false https://github.com/gpac/gpac.git .
./configure
make
make install

# HandBrake
cd /Temp
mkdir HandBrake
cd /Temp/HandBrake
HandBrakeVersion=$(curl -s https://api.github.com/repos/HandBrake/HandBrake/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
git clone -c advice.detachedHead=false --branch $HandBrakeVersion https://github.com/HandBrake/HandBrake.git .
./configure --launch-jobs=$(nproc) --enable-qsv --disable-gtk --launch
cd /Temp/HandBrake/build
mv HandBrakeCLI /usr/bin/handbrake
chmod +x /usr/bin/handbrake
cd /Temp/HandBrake
rm -rf .git

# HDR10Plus-Tool
cd /Temp
wget https://github.com/quietvoid/hdr10plus_tool/releases/latest/download/hdr10plus_tool-1.7.1-x86_64-unknown-linux-musl.tar.gz
7z x hdr10plus_tool-1.7.1-x86_64-unknown-linux-musl.tar.gz
7z x hdr10plus_tool-1.7.1-x86_64-unknown-linux-musl.tar
mv hdr10plus_tool /usr/bin/hdr10plus_tool
chmod +x /usr/bin/hdr10plus_tool

# N-M3U8DL-Re
cd /Temp
wget https://github.com/nilaoda/N_m3u8DL-RE/releases/latest/download/N_m3u8DL-RE_v0.5.1-beta_linux-musl-x64_20251029.tar.gz
7z x N_m3u8DL-RE_v0.5.1-beta_linux-musl-x64_20251029.tar.gz
7z x N_m3u8DL-RE_v0.5.1-beta_linux-musl-x64_20251029.tar
mv N_m3u8DL-RE /usr/bin/m3u8
chmod +x /usr/bin/m3u8

# NordVPN
cd /Temp
curl -fsSL https://downloads.nordcdn.com/apps/linux/install.sh | bash

# Rclone
cd /Temp
curl https://rclone.org/install.sh | bash

# Shaka-Packager
cd /Temp
wget https://github.com/shaka-project/shaka-packager/releases/download/v2.6.1/packager-linux-x64
mv packager-linux-x64 /usr/bin/shaka-packager
chmod +x /usr/bin/shaka-packager

# Usque
cd /Temp
wget https://github.com/Diniboy1123/usque/releases/latest/download/usque_1.4.1_linux_amd64.zip
7z x -y usque_1.4.1_linux_amd64.zip
mv usque /usr/bin/usque
chmod +x /usr/bin/usque

cd /
rm -rf /Temp

apk update
apk upgrade

apk del \
    autoconf automake bash boost-dev busybox c-ares-dev cargo cargo-c ccache clang-dev cmake dpkg g++ gawk gettext-dev jq lame-dev libass-dev libdrm-dev libffi-dev libpq-dev \
    libraw-dev libtheora-dev libtool libudev-zero-dev libva-dev libvorbis-dev libvpx-dev libxml2-dev m4 make meson musl-locales nasm ninja numactl-dev opus-dev patch pkgconf \
    pv sqlite-dev swig tar unzip x264-dev xz zip zlib-dev

rm -rf /root/.cache
rm -rf /tmp/*
rm -rf /var/cache/apk/*
rm -rf Dockerfile
rm -rf setup
