#!/bin/bash

apt update --yes
apt upgrade --yes

# Main Packages
apt install --yes --no-install-recommends \
    apt-utils aria2 ca-certificates curl git libmagic-dev locales mediainfo neofetch p7zip-full p7zip-rar tzdata wget

# Build Packages
apt install --yes --no-install-recommends \
    autoconf automake build-essential cmake g++ gcc gettext gpg-agent intltool libcurl4-openssl-dev libssl-dev make software-properties-common unzip zip

# Python Packages
apt install --yes --no-install-recommends \
    python-is-python3 python3-dev python3-pip
python -m pip install --upgrade pip

# HandBrake Packages
apt install --yes --no-install-recommends \
    libass-dev libbz2-dev libdrm-dev libfontconfig-dev libfreetype-dev libfribidi-dev libharfbuzz-dev libjansson-dev libjpeg-turbo8-dev liblzma-dev libmp3lame-dev \
    libnuma-dev libogg-dev libopus-dev libraw-dev libsamplerate0-dev libspeex-dev libtheora-dev libtool libtool-bin libturbojpeg0-dev libudev-dev libva-dev libvorbis-dev libvpx-dev \
    libx264-dev libxml2-dev m4 meson nasm ninja-build patch pkg-config tar

mkdir /Temp

locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
dpkg-reconfigure --frontend=noninteractive locales

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
dpkg-reconfigure --frontend=noninteractive tzdata

# AniDL
cd /Temp
wget https://github.com/anidl/multi-downloader-nx/releases/latest/download/multi-downloader-nx-linux-cli.7z
7z x multi-downloader-nx-linux-cli.7z
cd /Temp/multi-downloader-nx-linux-x64-cli
mv aniDL /usr/bin/anidl
chmod +x /usr/bin/anidl
anidl --service "crunchy" --dlFonts

# Bento4
cd /Temp
mkdir Bento4
cd /Temp/Bento4
git clone -c advice.detachedHead=false https://github.com/axiomatic-systems/Bento4.git .
cmake -DCMAKE_BUILD_TYPE=Release .
make
make install

# Code-Server
cd /Temp
curl -fsSL https://code-server.dev/install.sh | sh

# Fastfetch
cd /Temp
add-apt-repository --yes ppa:zhangsongcui3371/fastfetch
apt update --yes
apt install --yes --no-install-recommends fastfetch

# FFMPEG
cd /Temp
wget https://github.com/arakurumi/FFmpeg-Builds/releases/latest/download/ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar.xz
7z x ffmpeg-n7.1-latest-linux64-nonfree-7.1.tar
cd /Temp/ffmpeg-n7.1-latest-linux64-nonfree-7.1/bin
mv ffmpeg /usr/bin/ffmpeg
mv ffprobe /usr/bin/ffprobe
mv ffplay /usr/bin/ffplay
chmod +x /usr/bin/ffmpeg
chmod +x /usr/bin/ffprobe
chmod +x /usr/bin/ffplay

# Gost
cd /Temp
wget https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_linux_amd64v3.tar.gz
7z x gost_2.12.0_linux_amd64v3.tar.gz
7z x gost_2.12.0_linux_amd64v3.tar
mv gost /usr/bin/gost
chmod +x /usr/bin/gost

# GPAC
cd /Temp
mkdir GPAC
cd /Temp/GPAC
git clone -c advice.detachedHead=false https://github.com/gpac/gpac.git .
./configure
make
make install

# HandBrake
cd /Temp
mkdir HandBrake
cd /Temp/HandBrake
HandBrakeVersion=$(curl -s https://api.github.com/repos/HandBrake/HandBrake/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
git clone -c advice.detachedHead=false --branch $HandBrakeVersion https://github.com/HandBrake/HandBrake.git .
./configure --launch-jobs=$(nproc) --enable-qsv --disable-gtk --launch
cd /Temp/HandBrake/build
mv HandBrakeCLI /usr/bin/handbrake
chmod +x /usr/bin/handbrake
cd /Temp/HandBrake
rm -rf .git

# Hola-Proxy
cd /Temp
wget https://github.com/Snawoot/hola-proxy/releases/download/v1.17.0/hola-proxy.linux-amd64
mv hola-proxy.linux-amd64 /usr/bin/hola-proxy
chmod +x /usr/bin/hola-proxy

# MKVToolNix
cd /Temp
wget -O /usr/share/keyrings/gpg-pub-moritzbunkus.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ $(lsb_release -cs) main" >>/etc/apt/sources.list.d/mkvtoolnix.download.list
echo "deb-src [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ $(lsb_release -cs) main" >>/etc/apt/sources.list.d/mkvtoolnix.download.list
apt update --yes
apt install --yes --no-install-recommends mkvtoolnix

# N-M3U8DL-Re
cd /Temp
wget https://github.com/nilaoda/N_m3u8DL-RE/releases/latest/download/N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz
7z x N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar.gz
7z x N_m3u8DL-RE_v0.3.0-beta_linux-x64_20241203.tar
mv N_m3u8DL-RE /usr/bin/m3u8
chmod +x /usr/bin/m3u8

# NordVPN
cd /Temp
curl -fsSL https://downloads.nordcdn.com/apps/linux/install.sh | bash

# Opera-Proxy
cd /Temp
wget https://github.com/Snawoot/opera-proxy/releases/download/v1.9.0/opera-proxy.linux-amd64
mv opera-proxy.linux-amd64 /usr/bin/opera-proxy
chmod +x /usr/bin/opera-proxy

# Rclone
cd /Temp
curl https://rclone.org/install.sh | bash

# Shaka-Packager
cd /Temp
wget https://github.com/shaka-project/shaka-packager/releases/download/v2.6.1/packager-linux-x64
mv packager-linux-x64 /usr/bin/shaka-packager
chmod +x /usr/bin/shaka-packager

cd /
rm -rf /Temp

apt update --yes
apt upgrade --yes

apt remove --yes \
    autoconf automake build-essential cargo cmake g++ gcc gettext gpg-agent libass-dev libbz2-dev libdrm-dev libcurl4-openssl-dev libfontconfig-dev libfreetype-dev \
    libfribidi-dev libharfbuzz-dev liblzma-dev libmp3lame-dev libnuma-dev libogg-dev libopus-dev libraw-dev libsamplerate0-dev libssl-dev libtheora-dev libtool libtool-bin libudev-dev \
    libva-dev libvorbis-dev libvpx-dev libx264-dev libxml2-dev m4 make meson nasm ninja-build patch pkg-config software-properties-common tar unzip zip

apt autoclean --yes
apt autoremove --yes

rm -rf /root/.cache
rm -rf /tmp/*
rm -rf /var/cache/apk/*
rm -rf Dockerfile
rm -rf setup