#!/bin/bash

apt update --yes
apt upgrade --yes

# Main Packages
apt install --yes --no-install-recommends \
    apt-utils aria2 ca-certificates ccextractor curl fonts-firacode git libmagic-dev locales mediainfo neofetch p7zip-full p7zip-rar sox tzdata wget

# Build Packages
apt install --yes --no-install-recommends \
    autoconf automake build-essential cmake g++ gcc gettext gpg-agent intltool libcurl4-openssl-dev libssl-dev make software-properties-common unzip zip

# Python Packages
apt install --yes --no-install-recommends \
    python-is-python3 python3-dev python3-pip
python -m pip install --upgrade pip

mkdir /Temp

locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
dpkg-reconfigure --frontend=noninteractive locales

ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
dpkg-reconfigure --frontend=noninteractive tzdata

# AniDL
cd /Temp
wget https://github.com/anidl/multi-downloader-nx/releases/latest/download/multi-downloader-nx-linux-cli.7z
7z x -y multi-downloader-nx-linux-cli.7z
cd /Temp/multi-downloader-nx-linux-x64-cli
mv aniDL /usr/bin/anidl
chmod +x /usr/bin/anidl
anidl --service "crunchy" --dlFonts

# Bun
cd /root/Temp
curl -fsSL https://bun.sh/install | bash

# Bento4
cd /Temp
mkdir Bento4
cd /Temp/Bento4
git clone -c advice.detachedHead=false https://github.com/axiomatic-systems/Bento4.git .
cmake -DCMAKE_BUILD_TYPE=Release .
make -j$(nproc)
make install

# Code-Server
cd /Temp
curl -fsSL https://code-server.dev/install.sh | sh

# Dovi-Tool
cd /Temp
wget https://github.com/quietvoid/dovi_tool/releases/latest/dovi_tool-2.3.2-x86_64-unknown-linux-musl.tar.gz
7z x -y dovi_tool-2.3.2-x86_64-unknown-linux-musl.tar.gz
7z x -y dovi_tool-2.3.2-x86_64-unknown-linux-musl.tar
mv dovi_tool /usr/bin/dovi_tool
chmod +x /usr/bin/dovi_tool

# Fastfetch
cd /Temp
add-apt-repository --yes ppa:zhangsongcui3371/fastfetch
apt update --yes
apt install --yes --no-install-recommends fastfetch

# FFMPEG
cd /Temp
wget https://github.com/arakurumi/FFmpeg-Builds/releases/latest/download/ffmpeg-n8.1-latest-linux64-nonfree-8.1.tar.xz
7z x -y ffmpeg-n8.0-latest-linux64-nonfree-8.1.tar.xz
7z x -y ffmpeg-n8.0-latest-linux64-nonfree-8.1.tar
cd /Temp/ffmpeg-n8.0-latest-linux64-nonfree-8.1/bin
mv ffmpeg /usr/bin/ffmpeg
mv ffprobe /usr/bin/ffprobe
mv ffplay /usr/bin/ffplay
chmod +x /usr/bin/ffmpeg
chmod +x /usr/bin/ffprobe
chmod +x /usr/bin/ffplay

# Gost
cd /Temp
wget https://github.com/ginuerzh/gost/releases/latest/download/gost_2.12.0_linux_amd64v3.tar.gz
7z x -y gost_2.12.0_linux_amd64v3.tar.gz
7z x -y gost_2.12.0_linux_amd64v3.tar
mv gost /usr/bin/gost
chmod +x /usr/bin/gost

# GPAC
cd /Temp
wget https://download.tsi.telecom-paristech.fr/gpac/new_builds/gpac_latest_head_linux64.deb
apt install --yes --no-install-recommends ./gpac_latest_head_linux64.deb

# HandBrake
cd /Temp
mkdir HandBrake
cd /Temp/HandBrake
HandBrakeVersion=$(curl -s https://api.github.com/repos/HandBrake/HandBrake/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]')
git clone -c advice.detachedHead=false --branch $HandBrakeVersion https://github.com/HandBrake/HandBrake.git .
./configure --launch-jobs=$(nproc) --enable-qsv --disable-gtk --launch
cd /Temp/HandBrake/build
mv HandBrakeCLI /usr/bin/handbrake
chmod +x /usr/bin/handbrake
cd /Temp/HandBrake
rm -rf .git

# HDR10Plus-Tool
cd /Temp
wget https://github.com/quietvoid/hdr10plus_tool/releases/latest/download/hdr10plus_tool-1.7.2-x86_64-unknown-linux-musl.tar.gz
7z x hdr10plus_tool-1.7.2-x86_64-unknown-linux-musl.tar.gz
7z x hdr10plus_tool-1.7.2-x86_64-unknown-linux-musl.tar
mv hdr10plus_tool /usr/bin/hdr10plus_tool
chmod +x /usr/bin/hdr10plus_tool

# MKVToolNix
cd /Temp
wget -O /usr/share/keyrings/gpg-pub-moritzbunkus.gpg https://mkvtoolnix.download/gpg-pub-moritzbunkus.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ $(lsb_release -cs) main" >>/etc/apt/sources.list.d/mkvtoolnix.download.list
echo "deb-src [arch=amd64 signed-by=/usr/share/keyrings/gpg-pub-moritzbunkus.gpg] https://mkvtoolnix.download/ubuntu/ $(lsb_release -cs) main" >>/etc/apt/sources.list.d/mkvtoolnix.download.list
apt update --yes
apt install --yes --no-install-recommends mkvtoolnix

# N-M3U8DL-Re
cd /Temp
wget https://github.com/nilaoda/N_m3u8DL-RE/releases/latest/download/N_m3u8DL-RE_v0.5.1-beta_linux-x64_20251029.tar.gz
7z x -y N_m3u8DL-RE_v0.5.1-beta_linux-x64_20251029.tar.gz
7z x -y N_m3u8DL-RE_v0.5.1-beta_linux-x64_20251029.tar
mv N_m3u8DL-RE /usr/bin/m3u8
chmod +x /usr/bin/m3u8

# NordVPN
cd /Temp
curl -fsSL https://downloads.nordcdn.com/apps/linux/install.sh | bash

# Rclone
cd /Temp
curl https://rclone.org/install.sh | bash

# Shaka-Packager
cd /Temp
wget https://github.com/shaka-project/shaka-packager/releases/latest/download/packager-linux-x64
mv packager-linux-x64 /usr/bin/shaka-packager
chmod +x /usr/bin/shaka-packager

# Usque
cd /Temp
wget https://github.com/Diniboy1123/usque/releases/latest/download/usque_2.0.1_linux_amd64.zip
7z x -y usque_2.0.1_linux_amd64.zip
mv usque /usr/bin/usque
chmod +x /usr/bin/usque

cd /
rm -rf /Temp

apt update --yes
apt upgrade --yes

apt remove --yes \
    autoconf automake build-essential cmake g++ gcc gettext gpg-agent libcurl4-openssl-dev libssl-dev software-properties-common unzip zip

apt autoclean --yes
apt autoremove --yes

rm -rf /root/.cache
rm -rf /tmp/*
rm -rf /var/cache/apk/*
rm -rf Dockerfile
rm -rf setup
