name: Build and Push Alpine Image

on:
  push:
    paths:
      - "alpine/Dockerfile"
      - "alpine/setup"

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    name: Docker.io

    runs-on: ubuntu-24.04

    steps:
      - name: Login to Docker.io
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          tags: |
            alpine
          images: |
            arakurumi/myne
          labels: |
            org.opencontainers.image.authors=Kurumi <kqruumi@gmail.com>
            org.opencontainers.image.description=Docker Images for My Project
            org.opencontainers.image.licenses=Unlicense
            org.opencontainers.image.source=https://github.com/arakurumi/docker-myne
            org.opencontainers.image.title=Docker-Myne
            org.opencontainers.image.url=https://github.com/arakurumi/docker-myne
            org.opencontainers.image.version=alpine
          annotations: |
            org.opencontainers.image.description=Docker Images for My Project
            org.opencontainers.image.licenses=Unlicense
            org.opencontainers.image.source=https://github.com/arakurumi/docker-myne
            org.opencontainers.image.title=Docker-Myne
            org.opencontainers.image.url=https://github.com/arakurumi/docker-myne
            org.opencontainers.image.version=alpine

      - name: Build and Push to Docker.io
        uses: docker/build-push-action@master
        with:
          push: true
          context: "{{defaultContext}}:alpine"
          no-cache: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
